spring.application.name=calculadoraedenred

# URL com o nome do banco que você criou no Passo 2
spring.datasource.url=jdbc:postgresql://localhost:5432/edenred

# No Postgres.app, o user padrão costuma ser o seu nome no Mac (ex: marilialima)
# Se não funcionar, tente 'postgres'
spring.datasource.username=marilialima
spring.datasource.password=

# Isso faz a mágica de criar as tabelas para você
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true

